syntax = "proto3";

package game.region;

message RegionUpdate {
  oneof payload {
    LocationBlock location_block = 1;
    BulletShot bullet_shot = 2;
    PotionUse potion_use = 3;
    ItemDrop item_drop = 4;
  }
}

message ItemDrop {
  int32 inventory_index = 1;
  string item_kind = 2;
  int32 ammo = 3;
}

message PotionUse {
  PotionType potion_type = 1;
  int32 HowMuch=2;

  enum PotionType {
    health = 0;
    damage = 1;
  }
}

message LocationBlock {
  int32 x = 1;
  int32 y = 2;
}

message BulletShot {
  string gun_type = 1;
  float angle = 2;
  int32 count = 3;
  optional int32 x = 4;     // only set from server -> client
  optional int32 y = 5;     // only set from server -> client
  optional int32 ttl =  6;  // only set from server -> client
  optional int32 speed = 7; // only set from server -> client
}

message HandshakeStart {
  Kind kind = 1;
  oneof payload {
    string session_id = 2;
  }
  optional int32 user_id = 3; // only set from server -> client
  optional int32 health = 4;
  optional int32 money = 5;
  optional int32 pos_x = 6;
  optional int32 pos_y = 7;

  repeated int32 weapons = 8;
  repeated int32 potions = 9;
  repeated int32 ammo = 10; // NEW: Added to track ammo per weapon slot

  enum Kind {
    LOGIN = 0;
    SERVER_OK = 1;
    AUTH_FAIL = 2;
  }
}

message OtherPlayerData {
  oneof payload {
    LocationBlock new_location = 1;
    int32 HP = 2;
    OtherState state = 3;
  }
  int32 player_id = 4;
  enum OtherState {
    WALKING = 0;
    ATTACKING = 1;
  }
}

message ServerResponse {
  int32 sender_id = 1;
  oneof payload {
    LocationBlock move_self = 2; // force tp back - block invalid movements
    OtherPlayerData other_data = 3;
  }
  repeated BulletShot bullet_shot = 4;
}
