syntax = "proto3";

package game.region;


message ChatMessage {
  oneof mas {
    string message = 1;
  }
}

message RegionUpdate {
  oneof payload {
    LocationBlock location_block = 1;
    BulletShot bullet_shot = 2;
    PotionUse potion_use = 3;
  }
  optional uint64 seq_num = 4;
  optional int32 sender_id = 5;
}

message PotionUse {
  PotionType potion_type = 1;
  int32 HowMuch=2;

  enum PotionType {
    health = 0;
  }
}

message LocationBlock {
  int32 x = 1;
  int32 y = 2;
}

message BulletShot {
  string gun_type = 1;
  float angle = 2;
  int32 count = 3;
  optional int32 x = 4;     // only set from server -> client
  optional int32 y = 5;     // only set from server -> client
  optional int32 ttl =  6;  // only set from server -> client
  optional int32 speed = 7; // only set from server -> client
}

message HandshakeStart {
  Kind kind = 1;
  oneof payload {
    int32 session_id = 2;
  }
  optional int32 user_id = 3; // only set from server -> client

  enum Kind {
    LOGIN = 0;
    SERVER_OK = 1;
    SERVER_FAIL_INVALID_SESSION_ID = 2;
  }
}

message OtherPlayerData {
  oneof payload {
    LocationBlock new_location = 1;
    int32 HP = 2;
    OtherState state = 3;
  }
  int32 player_id = 4;
  enum OtherState {
    WALKING = 0;
    ATTACKING = 1;
    DESPAWNED = 2;
  }
}

message ServerResponse {
  int32 sender_id = 1;
  oneof payload {
    LocationBlock move_self = 2; // force tp back - block invalid movements
    OtherPlayerData other_data = 3;
  }
  repeated BulletShot bullet_shot = 4;
  optional uint64 seq_num = 5;
}
